const formStructure = {
  'foulath': {
    'Digital Transformation': [
      { name: 'Key Function / Service', label: 'Key Function / Service', type: 'text' },
      { name: 'Key Function / Service Owner(s)', label: 'Key Function / Service Owner(s)', type: 'text' },
      { name: 'Time From Start Of Incident', label: 'Time From Start Of Incident', type: 'text' },
      { name: 'Impact To Company', label: 'Impact To Company', type: 'text' },
      { name: 'Justification for Impact to Company (Based on Financial / Operational / Legal Reasons)', label: 'Justification for Impact to Company (Based on Financial / Operational / Legal Reasons)', type: 'text' },
      { name: 'Who is Impacted', label: 'Who is Impacted', type: 'text' },
      { name: 'Max. Tolerable Period of Disruption (MTPD)', label: 'Max. Tolerable Period of Disruption (MTPD)', type: 'text' },
      { name: 'Recovery Time Objective (RTO)', label: 'Recovery Time Objective (RTO)', type: 'text' },
      { name: 'Staff Requirement', label: 'Staff Requirement', type: 'number' },
      { name: 'Facilities & Workspace Requirements', label: 'Facilities & Workspace Requirements', type: 'text' },
      { name: 'Critical Records', label: 'Critical Records', type: 'text' },
      { name: 'Applications& Technology', label: 'Applications& Technology', type: 'text' },
      { name: 'Suppliers / Partners', label: 'Suppliers / Partners', type: 'text' },
      { name: 'Short-Term Workarounds?', label: 'Short-Term Workarounds?', type: 'text' },
      { name: 'Existing Response & Recovery Plans?', label: 'Existing Response & Recovery Plans?', type: 'text' },
      { name: 'MTDL Max. Tolerable Data Loss', label: 'MTDL Max. Tolerable Data Loss', type: 'text' },
      { name: 'RPO Recovery Point Objective', label: 'RPO Recovery Point Objective', type: 'text' },
      { name: 'Additional Information', label: 'Additional Information', type: 'text' }
    ],
    'Facility Management': [
      { name: 'Key Function / Service', label: 'Key Function / Service', type: 'text' },
      { name: 'Key Function / Service Owner(s)', label: 'Key Function / Service Owner(s)', type: 'text' },
      { name: 'Time From Start Of Incident', label: 'Time From Start Of Incident', type: 'text' },
      { name: 'Impact To Company', label: 'Impact To Company', type: 'text' },
      { name: 'Justification for Impact to Company (Based on Financial / Operational / Legal Reasons)', label: 'Justification for Impact to Company (Based on Financial / Operational / Legal Reasons)', type: 'text' },
      { name: 'Who is Impacted', label: 'Who is Impacted', type: 'text' },
      { name: 'Max. Tolerable Period of Disruption (MTPD)', label: 'Max. Tolerable Period of Disruption (MTPD)', type: 'text' },
      { name: 'Recovery Time Objective (RTO)', label: 'Recovery Time Objective (RTO)', type: 'text' },
      { name: 'Staff Requirement', label: 'Staff Requirement', type: 'number' },
      { name: 'Facilities & Workspace Requirements', label: 'Facilities & Workspace Requirements', type: 'text' },
      { name: 'Critical Records', label: 'Critical Records', type: 'text' },
      { name: 'Applications& Technology', label: 'Applications& Technology', type: 'text' },
      { name: 'Suppliers / Partners', label: 'Suppliers / Partners', type: 'text' },
      { name: 'Short-Term Workarounds?', label: 'Short-Term Workarounds?', type: 'text' },
      { name: 'Existing Response & Recovery Plans?', label: 'Existing Response & Recovery Plans?', type: 'text' },
      { name: 'MTDL Max. Tolerable Data Loss', label: 'MTDL Max. Tolerable Data Loss', type: 'text' },
      { name: 'RPO Recovery Point Objective', label: 'RPO Recovery Point Objective', type: 'text' },
      { name: 'Additional Information', label: 'Additional Information', type: 'text' }
    ],
    'Finance': [
      { name: 'Key Function / Service', label: 'Key Function / Service', type: 'text' },
      { name: 'Key Function / Service Owner(s)', label: 'Key Function / Service Owner(s)', type: 'text' },
      { name: 'Time From Start Of Incident', label: 'Time From Start Of Incident', type: 'text' },
      { name: 'Impact To Company', label: 'Impact To Company', type: 'text' },
      { name: 'Justification for Impact to Company (Based on Financial / Operational / Legal Reasons)', label: 'Justification for Impact to Company (Based on Financial / Operational / Legal Reasons)', type: 'text' },
      { name: 'Who is Impacted', label: 'Who is Impacted', type: 'text' },
      { name: 'Max. Tolerable Period of Disruption (MTPD)', label: 'Max. Tolerable Period of Disruption (MTPD)', type: 'text' },
      { name: 'Recovery Time Objective (RTO)', label: 'Recovery Time Objective (RTO)', type: 'text' },
      { name: 'Staff Requirement', label: 'Staff Requirement', type: 'number' },
      { name: 'Facilities & Workspace Requirements', label: 'Facilities & Workspace Requirements', type: 'text' },
      // { name: 'Critical Records', label: 'Critical Records', type: 'text' },
      { name: 'Applications& Technology', label: 'Applications& Technology', type: 'text' },
      { name: 'Suppliers / Partners', label: 'Suppliers / Partners', type: 'text' },
      { name: 'Short-Term Workarounds?', label: 'Short-Term Workarounds?', type: 'text' },
      { name: 'Existing Response & Recovery Plans?', label: 'Existing Response & Recovery Plans?', type: 'text' },
      { name: 'MTDL Max. Tolerable Data Loss', label: 'MTDL Max. Tolerable Data Loss', type: 'text' },
      { name: 'RPO Recovery Point Objective', label: 'RPO Recovery Point Objective', type: 'text' },
      { name: 'Additional Information', label: 'Additional Information', type: 'text' }
    ],
    'PR Government Relations': [
      { name: 'Key Function / Service', label: 'Key Function / Service', type: 'text' },
      { name: 'Key Function / Service Owner(s)', label: 'Key Function / Service Owner(s)', type: 'text' },
      { name: 'Time From Start Of Incident', label: 'Time From Start Of Incident', type: 'text' },
      { name: 'Impact To Company', label: 'Impact To Company', type: 'text' },
      { name: 'Justification for Impact to Company (Based on Financial / Operational / Legal Reasons)', label: 'Justification for Impact to Company (Based on Financial / Operational / Legal Reasons)', type: 'text' },
      { name: 'Who is Impacted', label: 'Who is Impacted', type: 'text' },
      { name: 'Max. Tolerable Period of Disruption (MTPD)', label: 'Max. Tolerable Period of Disruption (MTPD)', type: 'text' },
      { name: 'Recovery Time Objective (RTO)', label: 'Recovery Time Objective (RTO)', type: 'text' },
      { name: 'Staff Requirement', label: 'Staff Requirement', type: 'number' },
      { name: 'Facilities & Workspace Requirements', label: 'Facilities & Workspace Requirements', type: 'text' },
      { name: 'Critical Records', label: 'Critical Records', type: 'text' },
      { name: 'Applications& Technology', label: 'Applications& Technology', type: 'text' },
      { name: 'Suppliers / Partners', label: 'Suppliers / Partners', type: 'text' },
      { name: 'Short-Term Workarounds?', label: 'Short-Term Workarounds?', type: 'text' },
      { name: 'Existing Response & Recovery Plans?', label: 'Existing Response & Recovery Plans?', type: 'text' },
      { name: 'MTDL Max. Tolerable Data Loss', label: 'MTDL Max. Tolerable Data Loss', type: 'text' },
      { name: 'RPO Recovery Point Objective', label: 'RPO Recovery Point Objective', type: 'text' },
      { name: 'Additional Information', label: 'Additional Information', type: 'text' }
    ],
    'HR': [
      { name: 'Key Function / Service', label: 'Key Function / Service', type: 'text' },
      { name: 'Key Function / Service Owner(s)', label: 'Key Function / Service Owner(s)', type: 'text' },
      { name: 'Time From Start Of Incident', label: 'Time From Start Of Incident', type: 'text' },
      { name: 'Impact To Company', label: 'Impact To Company', type: 'text' },
      { name: 'Justification for Impact to Company (Based on Financial / Operational / Legal Reasons)', label: 'Justification for Impact to Company (Based on Financial / Operational / Legal Reasons)', type: 'text' },
      { name: 'Who is Impacted', label: 'Who is Impacted', type: 'text' },
      { name: 'Max. Tolerable Period of Disruption (MTPD)', label: 'Max. Tolerable Period of Disruption (MTPD)', type: 'text' },
      { name: 'Recovery Time Objective (RTO)', label: 'Recovery Time Objective (RTO)', type: 'text' },
      { name: 'Staff Requirement', label: 'Staff Requirement', type: 'number' },
      { name: 'Facilities & Workspace Requirements', label: 'Facilities & Workspace Requirements', type: 'text' },
      { name: 'Critical Records', label: 'Critical Records', type: 'text' },
      { name: 'Applications& Technology', label: 'Applications& Technology', type: 'text' },
      { name: 'Suppliers / Partners', label: 'Suppliers / Partners', type: 'text' },
      { name: 'Short-Term Workarounds?', label: 'Short-Term Workarounds?', type: 'text' },
      { name: 'Existing Response & Recovery Plans?', label: 'Existing Response & Recovery Plans?', type: 'text' },
      // { name: 'MTDL Max. Tolerable Data Loss', label: 'MTDL Max. Tolerable Data Loss', type: 'text' },
      // { name: 'RPO Recovery Point Objective', label: 'RPO Recovery Point Objective', type: 'text' },
      { name: 'Additional Information', label: 'Additional Information', type: 'text' }
    ],
    'Internal Audit': [
      { name: 'Key Function / Service', label: 'Key Function / Service', type: 'text' },
      { name: 'Key Function / Service Owner(s)', label: 'Key Function / Service Owner(s)', type: 'text' },
      { name: 'Time From Start Of Incident', label: 'Time From Start Of Incident', type: 'text' },
      { name: 'Impact To Company', label: 'Impact To Company', type: 'text' },
      { name: 'Justification for Impact to Company (Based on Financial / Operational / Legal Reasons)', label: 'Justification for Impact to Company (Based on Financial / Operational / Legal Reasons)', type: 'text' },
      { name: 'Who is Impacted', label: 'Who is Impacted', type: 'text' },
      { name: 'Max. Tolerable Period of Disruption (MTPD)', label: 'Max. Tolerable Period of Disruption (MTPD)', type: 'text' },
      { name: 'Recovery Time Objective (RTO)', label: 'Recovery Time Objective (RTO)', type: 'text' },
      { name: 'Staff Requirement', label: 'Staff Requirement', type: 'number' },
      { name: 'Facilities & Workspace Requirements', label: 'Facilities & Workspace Requirements', type: 'text' },
      { name: 'Critical Records', label: 'Critical Records', type: 'text' },
      { name: 'Applications& Technology', label: 'Applications& Technology', type: 'text' },
      { name: 'Suppliers / Partners', label: 'Suppliers / Partners', type: 'text' },
      { name: 'Short-Term Workarounds?', label: 'Short-Term Workarounds?', type: 'text' },
      { name: 'Existing Response & Recovery Plans?', label: 'Existing Response & Recovery Plans?', type: 'text' },
      { name: 'MTDL Max. Tolerable Data Loss', label: 'MTDL Max. Tolerable Data Loss', type: 'text' },
      { name: 'RPO Recovery Point Objective', label: 'RPO Recovery Point Objective', type: 'text' },
      { name: 'Additional Information', label: 'Additional Information', type: 'text' }
    ],
    'Legal': [
      { name: 'Key Function / Service', label: 'Key Function / Service', type: 'text' },
      { name: 'Key Function / Service Owner(s)', label: 'Key Function / Service Owner(s)', type: 'text' },
      { name: 'Time From Start Of Incident', label: 'Time From Start Of Incident', type: 'text' },
      { name: 'Impact To Company', label: 'Impact To Company', type: 'text' },
      { name: 'Justification for Impact to Company (Based on Financial / Operational / Legal Reasons)', label: 'Justification for Impact to Company (Based on Financial / Operational / Legal Reasons)', type: 'text' },
      { name: 'Who is Impacted', label: 'Who is Impacted', type: 'text' },
      { name: 'Max. Tolerable Period of Disruption (MTPD)', label: 'Max. Tolerable Period of Disruption (MTPD)', type: 'text' },
      { name: 'Recovery Time Objective (RTO)', label: 'Recovery Time Objective (RTO)', type: 'text' },
      { name: 'Staff Requirement', label: 'Staff Requirement', type: 'number' },
      { name: 'Facilities & Workspace Requirements', label: 'Facilities & Workspace Requirements', type: 'text' },
      { name: 'Critical Records', label: 'Critical Records', type: 'text' },
      { name: 'Applications& Technology', label: 'Applications& Technology', type: 'text' },
      { name: 'Suppliers / Partners', label: 'Suppliers / Partners', type: 'text' },
      { name: 'Short-Term Workarounds?', label: 'Short-Term Workarounds?', type: 'text' },
      { name: 'Existing Response & Recovery Plans?', label: 'Existing Response & Recovery Plans?', type: 'text' },
      { name: 'MTDL Max. Tolerable Data Loss', label: 'MTDL Max. Tolerable Data Loss', type: 'text' },
      { name: 'RPO Recovery Point Objective', label: 'RPO Recovery Point Objective', type: 'text' },
      { name: 'Additional Information', label: 'Additional Information', type: 'text' }
    ],
    'SAP': [
      { name: 'Key Function / Service', label: 'Key Function / Service', type: 'text' },
      { name: 'Key Function / Service Owner(s)', label: 'Key Function / Service Owner(s)', type: 'text' },
      { name: 'Time From Start Of Incident', label: 'Time From Start Of Incident', type: 'text' },
      { name: 'Impact To Company', label: 'Impact To Company', type: 'text' },
      { name: 'Justification for Impact to Company (Based on Financial / Operational / Legal Reasons)', label: 'Justification for Impact to Company (Based on Financial / Operational / Legal Reasons)', type: 'text' },
      { name: 'Who is Impacted', label: 'Who is Impacted', type: 'text' },
      { name: 'Max. Tolerable Period of Disruption (MTPD)', label: 'Max. Tolerable Period of Disruption (MTPD)', type: 'text' },
      { name: 'Recovery Time Objective (RTO)', label: 'Recovery Time Objective (RTO)', type: 'text' },
      { name: 'Staff Requirement', label: 'Staff Requirement', type: 'number' },
      { name: 'Facilities & Workspace Requirements', label: 'Facilities & Workspace Requirements', type: 'text' },
      { name: 'Critical Records', label: 'Critical Records', type: 'text' },
      { name: 'Applications& Technology', label: 'Applications& Technology', type: 'text' },
      { name: 'Suppliers / Partners', label: 'Suppliers / Partners', type: 'text' },
      { name: 'Short-Term Workarounds?', label: 'Short-Term Workarounds?', type: 'text' },
      { name: 'Existing Response & Recovery Plans?', label: 'Existing Response & Recovery Plans?', type: 'text' },
      { name: 'MTDL Max. Tolerable Data Loss', label: 'MTDL Max. Tolerable Data Loss', type: 'text' },
      { name: 'RPO Recovery Point Objective', label: 'RPO Recovery Point Objective', type: 'text' },
      { name: 'Additional Information', label: 'Additional Information', type: 'text' }
    ],
    'Capex & Opex': [
      { name: 'Key Function / Service', label: 'Key Function / Service', type: 'text' },
      { name: 'Key Function / Service Owner(s)', label: 'Key Function / Service Owner(s)', type: 'text' },
      { name: 'Time From Start Of Incident', label: 'Time From Start Of Incident', type: 'text' },
      { name: 'Impact To Company', label: 'Impact To Company', type: 'text' },
      { name: 'Justification for Impact to Company (Based on Financial / Operational / Legal Reasons)', label: 'Justification for Impact to Company (Based on Financial / Operational / Legal Reasons)', type: 'text' },
      { name: 'Who is Impacted', label: 'Who is Impacted', type: 'text' },
      { name: 'Max. Tolerable Period of Disruption (MTPD)', label: 'Max. Tolerable Period of Disruption (MTPD)', type: 'text' },
      { name: 'Recovery Time Objective (RTO)', label: 'Recovery Time Objective (RTO)', type: 'text' },
      { name: 'Staff Requirement', label: 'Staff Requirement', type: 'number' },
      { name: 'Facilities & Workspace Requirements', label: 'Facilities & Workspace Requirements', type: 'text' },
      { name: 'Critical Records', label: 'Critical Records', type: 'text' },
      { name: 'Applications& Technology', label: 'Applications& Technology', type: 'text' },
      { name: 'Suppliers / Partners', label: 'Suppliers / Partners', type: 'text' },
      { name: 'Short-Term Workarounds?', label: 'Short-Term Workarounds?', type: 'text' },
      { name: 'Existing Response & Recovery Plans?', label: 'Existing Response & Recovery Plans?', type: 'text' },
      { name: 'MTDL Max. Tolerable Data Loss', label: 'MTDL Max. Tolerable Data Loss', type: 'text' },
      { name: 'RPO Recovery Point Objective', label: 'RPO Recovery Point Objective', type: 'text' },
      { name: 'Additional Information', label: 'Additional Information', type: 'text' }
    ],
    'Consumables': [
      { name: 'Key Function / Service', label: 'Key Function / Service', type: 'text' },
      { name: 'Key Function / Service Owner(s)', label: 'Key Function / Service Owner(s)', type: 'text' },
      { name: 'Time From Start Of Incident', label: 'Time From Start Of Incident', type: 'text' },
      { name: 'Impact To Company', label: 'Impact To Company', type: 'text' },
      { name: 'Justification for Impact to Company (Based on Financial / Operational / Legal Reasons)', label: 'Justification for Impact to Company (Based on Financial / Operational / Legal Reasons)', type: 'text' },
      { name: 'Who is Impacted', label: 'Who is Impacted', type: 'text' },
      { name: 'Max. Tolerable Period of Disruption (MTPD)', label: 'Max. Tolerable Period of Disruption (MTPD)', type: 'text' },
      { name: 'Recovery Time Objective (RTO)', label: 'Recovery Time Objective (RTO)', type: 'text' },
      { name: 'Staff Requirement', label: 'Staff Requirement', type: 'number' },
      { name: 'Facilities & Workspace Requirements', label: 'Facilities & Workspace Requirements', type: 'text' },
      { name: 'Critical Records', label: 'Critical Records', type: 'text' },
      { name: 'Applications& Technology', label: 'Applications& Technology', type: 'text' },
      { name: 'Suppliers / Partners', label: 'Suppliers / Partners', type: 'text' },
      { name: 'Short-Term Workarounds?', label: 'Short-Term Workarounds?', type: 'text' },
      { name: 'Existing Response & Recovery Plans?', label: 'Existing Response & Recovery Plans?', type: 'text' },
      { name: 'MTDL Max. Tolerable Data Loss', label: 'MTDL Max. Tolerable Data Loss', type: 'text' },
      { name: 'RPO Recovery Point Objective', label: 'RPO Recovery Point Objective', type: 'text' },
      { name: 'Additional Information', label: 'Additional Information', type: 'text' }
    ],
    'ILIC': [
      { name: 'Key Function / Service', label: 'Key Function / Service', type: 'text' },
      { name: 'Key Function / Service Owner(s)', label: 'Key Function / Service Owner(s)', type: 'text' },
      { name: 'Time From Start Of Incident', label: 'Time From Start Of Incident', type: 'text' },
      { name: 'Impact To Company', label: 'Impact To Company', type: 'text' },
      { name: 'Justification for Impact to Company (Based on Financial / Operational / Legal Reasons)', label: 'Justification for Impact to Company (Based on Financial / Operational / Legal Reasons)', type: 'text' },
      { name: 'Who is Impacted', label: 'Who is Impacted', type: 'text' },
      { name: 'Max. Tolerable Period of Disruption (MTPD)', label: 'Max. Tolerable Period of Disruption (MTPD)', type: 'text' },
      { name: 'Recovery Time Objective (RTO)', label: 'Recovery Time Objective (RTO)', type: 'text' },
      { name: 'Staff Requirement', label: 'Staff Requirement', type: 'number' },
      { name: 'Facilities & Workspace Requirements', label: 'Facilities & Workspace Requirements', type: 'text' },
      { name: 'Critical Records', label: 'Critical Records', type: 'text' },
      { name: 'Applications& Technology', label: 'Applications& Technology', type: 'text' },
      { name: 'Suppliers / Partners', label: 'Suppliers / Partners', type: 'text' },
      { name: 'Short-Term Workarounds?', label: 'Short-Term Workarounds?', type: 'text' },
      { name: 'Existing Response & Recovery Plans?', label: 'Existing Response & Recovery Plans?', type: 'text' },
      { name: 'MTDL Max. Tolerable Data Loss', label: 'MTDL Max. Tolerable Data Loss', type: 'text' },
      { name: 'RPO Recovery Point Objective', label: 'RPO Recovery Point Objective', type: 'text' },
      { name: 'Additional Information', label: 'Additional Information', type: 'text' }
    ],
    'IS': [
      { name: 'Key Function / Service', label: 'Key Function / Service', type: 'text' },
      { name: 'Key Function / Service Owner(s)', label: 'Key Function / Service Owner(s)', type: 'text' },
      { name: 'Time From Start Of Incident', label: 'Time From Start Of Incident', type: 'text' },
      { name: 'Impact To Company', label: 'Impact To Company', type: 'text' },
      { name: 'Justification for Impact to Company (Based on Financial / Operational / Legal Reasons)', label: 'Justification for Impact to Company (Based on Financial / Operational / Legal Reasons)', type: 'text' },
      { name: 'Who is Impacted', label: 'Who is Impacted', type: 'text' },
      { name: 'Max. Tolerable Period of Disruption (MTPD)', label: 'Max. Tolerable Period of Disruption (MTPD)', type: 'text' },
      { name: 'Recovery Time Objective (RTO)', label: 'Recovery Time Objective (RTO)', type: 'text' },
      { name: 'Staff Requirement', label: 'Staff Requirement', type: 'number' },
      { name: 'Facilities & Workspace Requirements', label: 'Facilities & Workspace Requirements', type: 'text' },
      { name: 'Critical Records', label: 'Critical Records', type: 'text' },
      { name: 'Applications& Technology', label: 'Applications& Technology', type: 'text' },
      { name: 'Suppliers / Partners', label: 'Suppliers / Partners', type: 'text' },
      { name: 'Short-Term Workarounds?', label: 'Short-Term Workarounds?', type: 'text' },
      { name: 'Existing Response & Recovery Plans?', label: 'Existing Response & Recovery Plans?', type: 'text' },
      { name: 'MTDL Max. Tolerable Data Loss', label: 'MTDL Max. Tolerable Data Loss', type: 'text' },
      { name: 'RPO Recovery Point Objective', label: 'RPO Recovery Point Objective', type: 'text' },
      { name: 'Additional Information', label: 'Additional Information', type: 'text' }
    ],
  },
  'sulb': {
    'DR Production': [
      { name: 'Key Function / Service', label: 'Key Function / Service', type: 'text' },
      { name: 'Key Function / Service Owner(s)', label: 'Key Function / Service Owner(s)', type: 'text' },
      { name: 'Time From Start Of Incident', label: 'Time From Start Of Incident', type: 'text' },
      { name: 'Impact To Company', label: 'Impact To Company', type: 'text' },
      { name: 'Justification for Impact to Company (Based on Financial / Operational / Legal Reasons)', label: 'Justification for Impact to Company (Based on Financial / Operational / Legal Reasons)', type: 'text' },
      { name: 'Who is Impacted', label: 'Who is Impacted', type: 'text' },
      { name: 'Max. Tolerable Period of Disruption (MTPD)', label: 'Max. Tolerable Period of Disruption (MTPD)', type: 'text' },
      { name: 'Recovery Time Objective (RTO)', label: 'Recovery Time Objective (RTO)', type: 'text' },
      { name: 'Staff Requirement', label: 'Staff Requirement', type: 'number' },
      { name: 'Facilities & Workspace Requirements', label: 'Facilities & Workspace Requirements', type: 'text' },
      { name: 'Critical Records', label: 'Critical Records', type: 'text' },
      { name: 'Applications& Technology', label: 'Applications& Technology', type: 'text' },
      { name: 'Suppliers / Partners', label: 'Suppliers / Partners', type: 'text' },
      { name: 'Short-Term Workarounds?', label: 'Short-Term Workarounds?', type: 'text' },
      { name: 'Existing Response & Recovery Plans?', label: 'Existing Response & Recovery Plans?', type: 'text' },
      { name: 'MTDL Max. Tolerable Data Loss', label: 'MTDL Max. Tolerable Data Loss', type: 'text' },
      { name: 'RPO Recovery Point Objective', label: 'RPO Recovery Point Objective', type: 'text' },
      { name: 'Additional Information', label: 'Additional Information', type: 'text' }
    ],
    'HSM Production': [
      { name: 'Key Function / Service', label: 'Key Function / Service', type: 'text' },
      { name: 'Key Function / Service Owner(s)', label: 'Key Function / Service Owner(s)', type: 'text' },
      { name: 'Time From Start Of Incident', label: 'Time From Start Of Incident', type: 'text' },
      { name: 'Impact To Company', label: 'Impact To Company', type: 'text' },
      { name: 'Justification for Impact to Company (Based on Financial / Operational / Legal Reasons)', label: 'Justification for Impact to Company (Based on Financial / Operational / Legal Reasons)', type: 'text' },
      { name: 'Who is Impacted', label: 'Who is Impacted', type: 'text' },
      { name: 'Max. Tolerable Period of Disruption (MTPD)', label: 'Max. Tolerable Period of Disruption (MTPD)', type: 'text' },
      { name: 'Recovery Time Objective (RTO)', label: 'Recovery Time Objective (RTO)', type: 'text' },
      { name: 'Staff Requirement', label: 'Staff Requirement', type: 'number' },
      { name: 'Facilities & Workspace Requirements', label: 'Facilities & Workspace Requirements', type: 'text' },
      { name: 'Critical Records', label: 'Critical Records', type: 'text' },
      { name: 'Applications& Technology', label: 'Applications& Technology', type: 'text' },
      { name: 'Suppliers / Partners', label: 'Suppliers / Partners', type: 'text' },
      { name: 'Short-Term Workarounds?', label: 'Short-Term Workarounds?', type: 'text' },
      { name: 'Existing Response & Recovery Plans?', label: 'Existing Response & Recovery Plans?', type: 'text' },
      { name: 'MTDL Max. Tolerable Data Loss', label: 'MTDL Max. Tolerable Data Loss', type: 'text' },
      { name: 'RPO Recovery Point Objective', label: 'RPO Recovery Point Objective', type: 'text' },
      { name: 'Additional Information', label: 'Additional Information', type: 'text' }
    ],
    'Logistics': [
      { name: 'Key Function / Service', label: 'Key Function / Service', type: 'text' },
      { name: 'Key Function / Service Owner(s)', label: 'Key Function / Service Owner(s)', type: 'text' },
      { name: 'Time From Start Of Incident', label: 'Time From Start Of Incident', type: 'text' },
      { name: 'Impact To Company', label: 'Impact To Company', type: 'text' },
      { name: 'Justification for Impact to Company (Based on Financial / Operational / Legal Reasons)', label: 'Justification for Impact to Company (Based on Financial / Operational / Legal Reasons)', type: 'text' },
      { name: 'Who is Impacted', label: 'Who is Impacted', type: 'text' },
      { name: 'Max. Tolerable Period of Disruption (MTPD)', label: 'Max. Tolerable Period of Disruption (MTPD)', type: 'text' },
      { name: 'Recovery Time Objective (RTO)', label: 'Recovery Time Objective (RTO)', type: 'text' },
      { name: 'Staff Requirement', label: 'Staff Requirement', type: 'number' },
      { name: 'Facilities & Workspace Requirements', label: 'Facilities & Workspace Requirements', type: 'text' },
      { name: 'Critical Records', label: 'Critical Records', type: 'text' },
      { name: 'Applications& Technology', label: 'Applications& Technology', type: 'text' },
      { name: 'Suppliers / Partners', label: 'Suppliers / Partners', type: 'text' },
      { name: 'Short-Term Workarounds?', label: 'Short-Term Workarounds?', type: 'text' },
      { name: 'Existing Response & Recovery Plans?', label: 'Existing Response & Recovery Plans?', type: 'text' },
      { name: 'MTDL Max. Tolerable Data Loss', label: 'MTDL Max. Tolerable Data Loss', type: 'text' },
      { name: 'RPO Recovery Point Objective', label: 'RPO Recovery Point Objective', type: 'text' },
      { name: 'Additional Information', label: 'Additional Information', type: 'text' }
    ],
    'MSP Production': [
      { name: 'Key Function / Service', label: 'Key Function / Service', type: 'text' },
      { name: 'Key Function / Service Owner(s)', label: 'Key Function / Service Owner(s)', type: 'text' },
      { name: 'Time From Start Of Incident', label: 'Time From Start Of Incident', type: 'text' },
      { name: 'Impact To Company', label: 'Impact To Company', type: 'text' },
      { name: 'Justification for Impact to Company (Based on Financial / Operational / Legal Reasons)', label: 'Justification for Impact to Company (Based on Financial / Operational / Legal Reasons)', type: 'text' },
      { name: 'Who is Impacted', label: 'Who is Impacted', type: 'text' },
      { name: 'Max. Tolerable Period of Disruption (MTPD)', label: 'Max. Tolerable Period of Disruption (MTPD)', type: 'text' },
      { name: 'Recovery Time Objective (RTO)', label: 'Recovery Time Objective (RTO)', type: 'text' },
      { name: 'Staff Requirement', label: 'Staff Requirement', type: 'number' },
      { name: 'Facilities & Workspace Requirements', label: 'Facilities & Workspace Requirements', type: 'text' },
      { name: 'Critical Records', label: 'Critical Records', type: 'text' },
      { name: 'Applications& Technology', label: 'Applications& Technology', type: 'text' },
      { name: 'Suppliers / Partners', label: 'Suppliers / Partners', type: 'text' },
      { name: 'Short-Term Workarounds?', label: 'Short-Term Workarounds?', type: 'text' },
      { name: 'Existing Response & Recovery Plans?', label: 'Existing Response & Recovery Plans?', type: 'text' },
      { name: 'MTDL Max. Tolerable Data Loss', label: 'MTDL Max. Tolerable Data Loss', type: 'text' },
      { name: 'RPO Recovery Point Objective', label: 'RPO Recovery Point Objective', type: 'text' },
      { name: 'Additional Information', label: 'Additional Information', type: 'text' }
    ],
    'Production Planning': [
      { name: 'Key Function / Service', label: 'Key Function / Service', type: 'text' },
      { name: 'Key Function / Service Owner(s)', label: 'Key Function / Service Owner(s)', type: 'text' },
      { name: 'Time From Start Of Incident', label: 'Time From Start Of Incident', type: 'text' },
      { name: 'Impact To Company', label: 'Impact To Company', type: 'text' },
      { name: 'Justification for Impact to Company (Based on Financial / Operational / Legal Reasons)', label: 'Justification for Impact to Company (Based on Financial / Operational / Legal Reasons)', type: 'text' },
      { name: 'Who is Impacted', label: 'Who is Impacted', type: 'text' },
      { name: 'Max. Tolerable Period of Disruption (MTPD)', label: 'Max. Tolerable Period of Disruption (MTPD)', type: 'text' },
      { name: 'Recovery Time Objective (RTO)', label: 'Recovery Time Objective (RTO)', type: 'text' },
      { name: 'Staff Requirement', label: 'Staff Requirement', type: 'number' },
      { name: 'Facilities & Workspace Requirements', label: 'Facilities & Workspace Requirements', type: 'text' },
      { name: 'Critical Records', label: 'Critical Records', type: 'text' },
      { name: 'Applications& Technology', label: 'Applications& Technology', type: 'text' },
      { name: 'Suppliers / Partners', label: 'Suppliers / Partners', type: 'text' },
      { name: 'Short-Term Workarounds?', label: 'Short-Term Workarounds?', type: 'text' },
      { name: 'Existing Response & Recovery Plans?', label: 'Existing Response & Recovery Plans?', type: 'text' },
      { name: 'MTDL Max. Tolerable Data Loss', label: 'MTDL Max. Tolerable Data Loss', type: 'text' },
      { name: 'RPO Recovery Point Objective', label: 'RPO Recovery Point Objective', type: 'text' },
      { name: 'Additional Information', label: 'Additional Information', type: 'text' }
    ],
    'Quality Assurance': [
      { name: 'Key Function / Service', label: 'Key Function / Service', type: 'text' },
      { name: 'Key Function / Service Owner(s)', label: 'Key Function / Service Owner(s)', type: 'text' },
      { name: 'Time From Start Of Incident', label: 'Time From Start Of Incident', type: 'text' },
      { name: 'Impact To Company', label: 'Impact To Company', type: 'text' },
      { name: 'Justification for Impact to Company (Based on Financial / Operational / Legal Reasons)', label: 'Justification for Impact to Company (Based on Financial / Operational / Legal Reasons)', type: 'text' },
      { name: 'Who is Impacted', label: 'Who is Impacted', type: 'text' },
      { name: 'Max. Tolerable Period of Disruption (MTPD)', label: 'Max. Tolerable Period of Disruption (MTPD)', type: 'text' },
      { name: 'Recovery Time Objective (RTO)', label: 'Recovery Time Objective (RTO)', type: 'text' },
      { name: 'Staff Requirement', label: 'Staff Requirement', type: 'number' },
      { name: 'Facilities & Workspace Requirements', label: 'Facilities & Workspace Requirements', type: 'text' },
      { name: 'Critical Records', label: 'Critical Records', type: 'text' },
      { name: 'Applications& Technology', label: 'Applications& Technology', type: 'text' },
      { name: 'Suppliers / Partners', label: 'Suppliers / Partners', type: 'text' },
      { name: 'Short-Term Workarounds?', label: 'Short-Term Workarounds?', type: 'text' },
      { name: 'Existing Response & Recovery Plans?', label: 'Existing Response & Recovery Plans?', type: 'text' },
      { name: 'MTDL Max. Tolerable Data Loss', label: 'MTDL Max. Tolerable Data Loss', type: 'text' },
      { name: 'RPO Recovery Point Objective', label: 'RPO Recovery Point Objective', type: 'text' },
      { name: 'Additional Information', label: 'Additional Information', type: 'text' }
    ],
    'Quality Control': [
      { name: 'Key Function / Service', label: 'Key Function / Service', type: 'text' },
      { name: 'Key Function / Service Owner(s)', label: 'Key Function / Service Owner(s)', type: 'text' },
      { name: 'Time From Start Of Incident', label: 'Time From Start Of Incident', type: 'text' },
      { name: 'Impact To Company', label: 'Impact To Company', type: 'text' },
      { name: 'Justification for Impact to Company (Based on Financial / Operational / Legal Reasons)', label: 'Justification for Impact to Company (Based on Financial / Operational / Legal Reasons)', type: 'text' },
      { name: 'Who is Impacted', label: 'Who is Impacted', type: 'text' },
      { name: 'Max. Tolerable Period of Disruption (MTPD)', label: 'Max. Tolerable Period of Disruption (MTPD)', type: 'text' },
      { name: 'Recovery Time Objective (RTO)', label: 'Recovery Time Objective (RTO)', type: 'text' },
      { name: 'Staff Requirement', label: 'Staff Requirement', type: 'number' },
      { name: 'Facilities & Workspace Requirements', label: 'Facilities & Workspace Requirements', type: 'text' },
      { name: 'Critical Records', label: 'Critical Records', type: 'text' },
      { name: 'Applications& Technology', label: 'Applications& Technology', type: 'text' },
      { name: 'Suppliers / Partners', label: 'Suppliers / Partners', type: 'text' },
      { name: 'Short-Term Workarounds?', label: 'Short-Term Workarounds?', type: 'text' },
      { name: 'Existing Response & Recovery Plans?', label: 'Existing Response & Recovery Plans?', type: 'text' },
      { name: 'MTDL Max. Tolerable Data Loss', label: 'MTDL Max. Tolerable Data Loss', type: 'text' },
      { name: 'RPO Recovery Point Objective', label: 'RPO Recovery Point Objective', type: 'text' },
      { name: 'Additional Information', label: 'Additional Information', type: 'text' }
    ],
    'Safety & Environment': [
      { name: 'Key Function / Service', label: 'Key Function / Service', type: 'text' },
      { name: 'Key Function / Service Owner(s)', label: 'Key Function / Service Owner(s)', type: 'text' },
      { name: 'Time From Start Of Incident', label: 'Time From Start Of Incident', type: 'text' },
      { name: 'Impact To Company', label: 'Impact To Company', type: 'text' },
      { name: 'Justification for Impact to Company (Based on Financial / Operational / Legal Reasons)', label: 'Justification for Impact to Company (Based on Financial / Operational / Legal Reasons)', type: 'text' },
      { name: 'Who is Impacted', label: 'Who is Impacted', type: 'text' },
      { name: 'Max. Tolerable Period of Disruption (MTPD)', label: 'Max. Tolerable Period of Disruption (MTPD)', type: 'text' },
      { name: 'Recovery Time Objective (RTO)', label: 'Recovery Time Objective (RTO)', type: 'text' },
      { name: 'Staff Requirement', label: 'Staff Requirement', type: 'number' },
      { name: 'Facilities & Workspace Requirements', label: 'Facilities & Workspace Requirements', type: 'text' },
      { name: 'Critical Records', label: 'Critical Records', type: 'text' },
      { name: 'Applications& Technology', label: 'Applications& Technology', type: 'text' },
      { name: 'Suppliers / Partners', label: 'Suppliers / Partners', type: 'text' },
      { name: 'Short-Term Workarounds?', label: 'Short-Term Workarounds?', type: 'text' },
      { name: 'Existing Response & Recovery Plans?', label: 'Existing Response & Recovery Plans?', type: 'text' },
      { name: 'MTDL Max. Tolerable Data Loss', label: 'MTDL Max. Tolerable Data Loss', type: 'text' },
      { name: 'RPO Recovery Point Objective', label: 'RPO Recovery Point Objective', type: 'text' },
      { name: 'Additional Information', label: 'Additional Information', type: 'text' }
    ],
    'Sales & Marketing': [
      { name: 'Key Function / Service', label: 'Key Function / Service', type: 'text' },
      { name: 'Key Function / Service Owner(s)', label: 'Key Function / Service Owner(s)', type: 'text' },
      { name: 'Time From Start Of Incident', label: 'Time From Start Of Incident', type: 'text' },
      { name: 'Impact To Company', label: 'Impact To Company', type: 'text' },
      { name: 'Justification for Impact to Company (Based on Financial / Operational / Legal Reasons)', label: 'Justification for Impact to Company (Based on Financial / Operational / Legal Reasons)', type: 'text' },
      { name: 'Who is Impacted', label: 'Who is Impacted', type: 'text' },
      { name: 'Max. Tolerable Period of Disruption (MTPD)', label: 'Max. Tolerable Period of Disruption (MTPD)', type: 'text' },
      { name: 'Recovery Time Objective (RTO)', label: 'Recovery Time Objective (RTO)', type: 'text' },
      { name: 'Staff Requirement', label: 'Staff Requirement', type: 'number' },
      { name: 'Facilities & Workspace Requirements', label: 'Facilities & Workspace Requirements', type: 'text' },
      { name: 'Critical Records', label: 'Critical Records', type: 'text' },
      { name: 'Applications& Technology', label: 'Applications& Technology', type: 'text' },
      { name: 'Suppliers / Partners', label: 'Suppliers / Partners', type: 'text' },
      { name: 'Short-Term Workarounds?', label: 'Short-Term Workarounds?', type: 'text' },
      { name: 'Existing Response & Recovery Plans?', label: 'Existing Response & Recovery Plans?', type: 'text' },
      { name: 'MTDL Max. Tolerable Data Loss', label: 'MTDL Max. Tolerable Data Loss', type: 'text' },
      { name: 'RPO Recovery Point Objective', label: 'RPO Recovery Point Objective', type: 'text' },
      { name: 'Additional Information', label: 'Additional Information', type: 'text' }
    ],
  },
  'sulb saudi': {
    'Sales & Marketing': [
      { name: 'Key Function / Service', label: 'Key Function / Service', type: 'text' },
      { name: 'Key Function / Service Owner(s)', label: 'Key Function / Service Owner(s)', type: 'text' },
      { name: 'Time From Start Of Incident', label: 'Time From Start Of Incident', type: 'text' },
      { name: 'Impact To Company', label: 'Impact To Company', type: 'text' },
      { name: 'Justification for Impact to Company (Based on Financial / Operational / Legal Reasons)', label: 'Justification for Impact to Company (Based on Financial / Operational / Legal Reasons)', type: 'text' },
      { name: 'Who is Impacted', label: 'Who is Impacted', type: 'text' },
      { name: 'Max. Tolerable Period of Disruption (MTPD)', label: 'Max. Tolerable Period of Disruption (MTPD)', type: 'text' },
      { name: 'Recovery Time Objective (RTO)', label: 'Recovery Time Objective (RTO)', type: 'text' },
      { name: 'Staff Requirement', label: 'Staff Requirement', type: 'number' },
      { name: 'Facilities & Workspace Requirements', label: 'Facilities & Workspace Requirements', type: 'text' },
      { name: 'Critical Records', label: 'Critical Records', type: 'text' },
      { name: 'Applications& Technology', label: 'Applications& Technology', type: 'text' },
      { name: 'Suppliers / Partners', label: 'Suppliers / Partners', type: 'text' },
      { name: 'Short-Term Workarounds?', label: 'Short-Term Workarounds?', type: 'text' },
      { name: 'Existing Response & Recovery Plans?', label: 'Existing Response & Recovery Plans?', type: 'text' },
      { name: 'MTDL Max. Tolerable Data Loss', label: 'MTDL Max. Tolerable Data Loss', type: 'text' },
      { name: 'RPO Recovery Point Objective', label: 'RPO Recovery Point Objective', type: 'text' },
      { name: 'Additional Information', label: 'Additional Information', type: 'text' }
    ],
    'Electrical Maintenance': [
      { name: 'Key Function / Service', label: 'Key Function / Service', type: 'text' },
      { name: 'Key Function / Service Owner(s)', label: 'Key Function / Service Owner(s)', type: 'text' },
      { name: 'Time From Start Of Incident', label: 'Time From Start Of Incident', type: 'text' },
      { name: 'Impact To Company', label: 'Impact To Company', type: 'text' },
      { name: 'Justification for Impact to Company (Based on Financial / Operational / Legal Reasons)', label: 'Justification for Impact to Company (Based on Financial / Operational / Legal Reasons)', type: 'text' },
      { name: 'Who is Impacted', label: 'Who is Impacted', type: 'text' },
      { name: 'Max. Tolerable Period of Disruption (MTPD)', label: 'Max. Tolerable Period of Disruption (MTPD)', type: 'text' },
      { name: 'Recovery Time Objective (RTO)', label: 'Recovery Time Objective (RTO)', type: 'text' },
      { name: 'Staff Requirement', label: 'Staff Requirement', type: 'number' },
      { name: 'Facilities & Workspace Requirements', label: 'Facilities & Workspace Requirements', type: 'text' },
      { name: 'Critical Records', label: 'Critical Records', type: 'text' },
      { name: 'Applications& Technology', label: 'Applications& Technology', type: 'text' },
      { name: 'Suppliers / Partners', label: 'Suppliers / Partners', type: 'text' },
      { name: 'Short-Term Workarounds?', label: 'Short-Term Workarounds?', type: 'text' },
      { name: 'Existing Response & Recovery Plans?', label: 'Existing Response & Recovery Plans?', type: 'text' },
      { name: 'MTDL Max. Tolerable Data Loss', label: 'MTDL Max. Tolerable Data Loss', type: 'text' },
      { name: 'RPO Recovery Point Objective', label: 'RPO Recovery Point Objective', type: 'text' },
      { name: 'Additional Information', label: 'Additional Information', type: 'text' }
    ],
    'Logistics': [
      { name: 'Key Function / Service', label: 'Key Function / Service', type: 'text' },
      { name: 'Key Function / Service Owner(s)', label: 'Key Function / Service Owner(s)', type: 'text' },
      { name: 'Time From Start Of Incident', label: 'Time From Start Of Incident', type: 'text' },
      { name: 'Impact To Company', label: 'Impact To Company', type: 'text' },
      { name: 'Justification for Impact to Company (Based on Financial / Operational / Legal Reasons)', label: 'Justification for Impact to Company (Based on Financial / Operational / Legal Reasons)', type: 'text' },
      { name: 'Who is Impacted', label: 'Who is Impacted', type: 'text' },
      { name: 'Max. Tolerable Period of Disruption (MTPD)', label: 'Max. Tolerable Period of Disruption (MTPD)', type: 'text' },
      { name: 'Recovery Time Objective (RTO)', label: 'Recovery Time Objective (RTO)', type: 'text' },
      { name: 'Staff Requirement', label: 'Staff Requirement', type: 'number' },
      { name: 'Facilities & Workspace Requirements', label: 'Facilities & Workspace Requirements', type: 'text' },
      { name: 'Critical Records', label: 'Critical Records', type: 'text' },
      { name: 'Applications& Technology', label: 'Applications& Technology', type: 'text' },
      { name: 'Suppliers / Partners', label: 'Suppliers / Partners', type: 'text' },
      { name: 'Short-Term Workarounds?', label: 'Short-Term Workarounds?', type: 'text' },
      { name: 'Existing Response & Recovery Plans?', label: 'Existing Response & Recovery Plans?', type: 'text' },
      { name: 'MTDL Max. Tolerable Data Loss', label: 'MTDL Max. Tolerable Data Loss', type: 'text' },
      { name: 'RPO Recovery Point Objective', label: 'RPO Recovery Point Objective', type: 'text' },
      { name: 'Additional Information', label: 'Additional Information', type: 'text' }
    ],
    'HR and Administration': [
      { name: 'Key Function / Service', label: 'Key Function / Service', type: 'text' },
      { name: 'Key Function / Service Owner(s)', label: 'Key Function / Service Owner(s)', type: 'text' },
      { name: 'Time From Start Of Incident', label: 'Time From Start Of Incident', type: 'text' },
      { name: 'Impact To Company', label: 'Impact To Company', type: 'text' },
      { name: 'Justification for Impact to Company (Based on Financial / Operational / Legal Reasons)', label: 'Justification for Impact to Company (Based on Financial / Operational / Legal Reasons)', type: 'text' },
      { name: 'Who is Impacted', label: 'Who is Impacted', type: 'text' },
      { name: 'Max. Tolerable Period of Disruption (MTPD)', label: 'Max. Tolerable Period of Disruption (MTPD)', type: 'text' },
      { name: 'Recovery Time Objective (RTO)', label: 'Recovery Time Objective (RTO)', type: 'text' },
      { name: 'Staff Requirement', label: 'Staff Requirement', type: 'number' },
      { name: 'Facilities & Workspace Requirements', label: 'Facilities & Workspace Requirements', type: 'text' },
      { name: 'Critical Records', label: 'Critical Records', type: 'text' },
      { name: 'Applications& Technology', label: 'Applications& Technology', type: 'text' },
      { name: 'Suppliers / Partners', label: 'Suppliers / Partners', type: 'text' },
      { name: 'Short-Term Workarounds?', label: 'Short-Term Workarounds?', type: 'text' },
      { name: 'Existing Response & Recovery Plans?', label: 'Existing Response & Recovery Plans?', type: 'text' },
      { name: 'MTDL Max. Tolerable Data Loss', label: 'MTDL Max. Tolerable Data Loss', type: 'text' },
      { name: 'RPO Recovery Point Objective', label: 'RPO Recovery Point Objective', type: 'text' },
      { name: 'Additional Information', label: 'Additional Information', type: 'text' }
    ],
    'Mechanical Maintenance': [
      { name: 'Key Function / Service', label: 'Key Function / Service', type: 'text' },
      { name: 'Key Function / Service Owner(s)', label: 'Key Function / Service Owner(s)', type: 'text' },
      { name: 'Time From Start Of Incident', label: 'Time From Start Of Incident', type: 'text' },
      { name: 'Impact To Company', label: 'Impact To Company', type: 'text' },
      { name: 'Justification for Impact to Company (Based on Financial / Operational / Legal Reasons)', label: 'Justification for Impact to Company (Based on Financial / Operational / Legal Reasons)', type: 'text' },
      { name: 'Who is Impacted', label: 'Who is Impacted', type: 'text' },
      { name: 'Max. Tolerable Period of Disruption (MTPD)', label: 'Max. Tolerable Period of Disruption (MTPD)', type: 'text' },
      { name: 'Recovery Time Objective (RTO)', label: 'Recovery Time Objective (RTO)', type: 'text' },
      { name: 'Staff Requirement', label: 'Staff Requirement', type: 'number' },
      { name: 'Facilities & Workspace Requirements', label: 'Facilities & Workspace Requirements', type: 'text' },
      { name: 'Critical Records', label: 'Critical Records', type: 'text' },
      { name: 'Applications& Technology', label: 'Applications& Technology', type: 'text' },
      { name: 'Suppliers / Partners', label: 'Suppliers / Partners', type: 'text' },
      { name: 'Short-Term Workarounds?', label: 'Short-Term Workarounds?', type: 'text' },
      { name: 'Existing Response & Recovery Plans?', label: 'Existing Response & Recovery Plans?', type: 'text' },
      { name: 'MTDL Max. Tolerable Data Loss', label: 'MTDL Max. Tolerable Data Loss', type: 'text' },
      { name: 'RPO Recovery Point Objective', label: 'RPO Recovery Point Objective', type: 'text' },
      { name: 'Additional Information', label: 'Additional Information', type: 'text' }
    ],
    'Production Planning & Control': [
      { name: 'Key Function / Service', label: 'Key Function / Service', type: 'text' },
      { name: 'Key Function / Service Owner(s)', label: 'Key Function / Service Owner(s)', type: 'text' },
      { name: 'Time From Start Of Incident', label: 'Time From Start Of Incident', type: 'text' },
      { name: 'Impact To Company', label: 'Impact To Company', type: 'text' },
      { name: 'Justification for Impact to Company (Based on Financial / Operational / Legal Reasons)', label: 'Justification for Impact to Company (Based on Financial / Operational / Legal Reasons)', type: 'text' },
      { name: 'Who is Impacted', label: 'Who is Impacted', type: 'text' },
      { name: 'Max. Tolerable Period of Disruption (MTPD)', label: 'Max. Tolerable Period of Disruption (MTPD)', type: 'text' },
      { name: 'Recovery Time Objective (RTO)', label: 'Recovery Time Objective (RTO)', type: 'text' },
      { name: 'Staff Requirement', label: 'Staff Requirement', type: 'number' },
      { name: 'Facilities & Workspace Requirements', label: 'Facilities & Workspace Requirements', type: 'text' },
      { name: 'Critical Records', label: 'Critical Records', type: 'text' },
      { name: 'Applications& Technology', label: 'Applications& Technology', type: 'text' },
      { name: 'Suppliers / Partners', label: 'Suppliers / Partners', type: 'text' },
      { name: 'Short-Term Workarounds?', label: 'Short-Term Workarounds?', type: 'text' },
      { name: 'Existing Response & Recovery Plans?', label: 'Existing Response & Recovery Plans?', type: 'text' },
      { name: 'MTDL Max. Tolerable Data Loss', label: 'MTDL Max. Tolerable Data Loss', type: 'text' },
      { name: 'RPO Recovery Point Objective', label: 'RPO Recovery Point Objective', type: 'text' },
      { name: 'Additional Information', label: 'Additional Information', type: 'text' }
    ],
    'Quality': [
      { name: 'Key Function / Service', label: 'Key Function / Service', type: 'text' },
      { name: 'Key Function / Service Owner(s)', label: 'Key Function / Service Owner(s)', type: 'text' },
      { name: 'Time From Start Of Incident', label: 'Time From Start Of Incident', type: 'text' },
      { name: 'Impact To Company', label: 'Impact To Company', type: 'text' },
      { name: 'Justification for Impact to Company (Based on Financial / Operational / Legal Reasons)', label: 'Justification for Impact to Company (Based on Financial / Operational / Legal Reasons)', type: 'text' },
      { name: 'Who is Impacted', label: 'Who is Impacted', type: 'text' },
      { name: 'Max. Tolerable Period of Disruption (MTPD)', label: 'Max. Tolerable Period of Disruption (MTPD)', type: 'text' },
      { name: 'Recovery Time Objective (RTO)', label: 'Recovery Time Objective (RTO)', type: 'text' },
      { name: 'Staff Requirement', label: 'Staff Requirement', type: 'number' },
      { name: 'Facilities & Workspace Requirements', label: 'Facilities & Workspace Requirements', type: 'text' },
      // { name: 'Critical Records', label: 'Critical Records', type: 'text' },
      { name: 'Applications& Technology', label: 'Applications& Technology', type: 'text' },
      { name: 'Suppliers / Partners', label: 'Suppliers / Partners', type: 'text' },
      { name: 'Short-Term Workarounds?', label: 'Short-Term Workarounds?', type: 'text' },
      { name: 'Existing Response & Recovery Plans?', label: 'Existing Response & Recovery Plans?', type: 'text' },
      { name: 'MTDL Max. Tolerable Data Loss', label: 'MTDL Max. Tolerable Data Loss', type: 'text' },
      { name: 'RPO Recovery Point Objective', label: 'RPO Recovery Point Objective', type: 'text' },
      { name: 'Additional Information', label: 'Additional Information', type: 'text' }
    ],
    'Rolling Mill & Roll Shop': [
      { name: 'Key Function / Service', label: 'Key Function / Service', type: 'text' },
      { name: 'Key Function / Service Owner(s)', label: 'Key Function / Service Owner(s)', type: 'text' },
      { name: 'Time From Start Of Incident', label: 'Time From Start Of Incident', type: 'text' },
      { name: 'Impact To Company', label: 'Impact To Company', type: 'text' },
      { name: 'Justification for Impact to Company (Based on Financial / Operational / Legal Reasons)', label: 'Justification for Impact to Company (Based on Financial / Operational / Legal Reasons)', type: 'text' },
      { name: 'Who is Impacted', label: 'Who is Impacted', type: 'text' },
      { name: 'Max. Tolerable Period of Disruption (MTPD)', label: 'Max. Tolerable Period of Disruption (MTPD)', type: 'text' },
      { name: 'Recovery Time Objective (RTO)', label: 'Recovery Time Objective (RTO)', type: 'text' },
      { name: 'Staff Requirement', label: 'Staff Requirement', type: 'number' },
      { name: 'Facilities & Workspace Requirements', label: 'Facilities & Workspace Requirements', type: 'text' },
      { name: 'Critical Records', label: 'Critical Records', type: 'text' },
      { name: 'Applications& Technology', label: 'Applications& Technology', type: 'text' },
      { name: 'Suppliers / Partners', label: 'Suppliers / Partners', type: 'text' },
      { name: 'Short-Term Workarounds?', label: 'Short-Term Workarounds?', type: 'text' },
      { name: 'Existing Response & Recovery Plans?', label: 'Existing Response & Recovery Plans?', type: 'text' },
      { name: 'MTDL Max. Tolerable Data Loss', label: 'MTDL Max. Tolerable Data Loss', type: 'text' },
      { name: 'RPO Recovery Point Objective', label: 'RPO Recovery Point Objective', type: 'text' },
      { name: 'Additional Information', label: 'Additional Information', type: 'text' }
    ],
    'Safety': [
      { name: 'Key Function / Service', label: 'Key Function / Service', type: 'text' },
      { name: 'Key Function / Service Owner(s)', label: 'Key Function / Service Owner(s)', type: 'text' },
      { name: 'Time From Start Of Incident', label: 'Time From Start Of Incident', type: 'text' },
      { name: 'Impact To Company', label: 'Impact To Company', type: 'text' },
      { name: 'Justification for Impact to Company (Based on Financial / Operational / Legal Reasons)', label: 'Justification for Impact to Company (Based on Financial / Operational / Legal Reasons)', type: 'text' },
      { name: 'Who is Impacted', label: 'Who is Impacted', type: 'text' },
      { name: 'Max. Tolerable Period of Disruption (MTPD)', label: 'Max. Tolerable Period of Disruption (MTPD)', type: 'text' },
      { name: 'Recovery Time Objective (RTO)', label: 'Recovery Time Objective (RTO)', type: 'text' },
      { name: 'Staff Requirement', label: 'Staff Requirement', type: 'number' },
      { name: 'Facilities & Workspace Requirements', label: 'Facilities & Workspace Requirements', type: 'text' },
      { name: 'Critical Records', label: 'Critical Records', type: 'text' },
      { name: 'Applications& Technology', label: 'Applications& Technology', type: 'text' },
      { name: 'Suppliers / Partners', label: 'Suppliers / Partners', type: 'text' },
      { name: 'Short-Term Workarounds?', label: 'Short-Term Workarounds?', type: 'text' },
      { name: 'Existing Response & Recovery Plans?', label: 'Existing Response & Recovery Plans?', type: 'text' },
      { name: 'MTDL Max. Tolerable Data Loss', label: 'MTDL Max. Tolerable Data Loss', type: 'text' },
      { name: 'RPO Recovery Point Objective', label: 'RPO Recovery Point Objective', type: 'text' },
      { name: 'Additional Information', label: 'Additional Information', type: 'text' }
    ]
  },
    'bahrain steel': {
    'OA File': [
      { name: 'Key Function / Service', label: 'Key Function / Service', type: 'text' },
      { name: 'Key Function / Service Owner(s)', label: 'Key Function / Service Owner(s)', type: 'text' },
      { name: 'Time From Start Of Incident', label: 'Time From Start Of Incident', type: 'text' },
      { name: 'Impact To Company', label: 'Impact To Company', type: 'text' },
      { name: 'Justification for Impact to Company (Based on Financial / Operational / Legal Reasons)', label: 'Justification for Impact to Company (Based on Financial / Operational / Legal Reasons)', type: 'text' },
      { name: 'Who is Impacted', label: 'Who is Impacted', type: 'text' },
      { name: 'Max. Tolerable Period of Disruption (MTPD)', label: 'Max. Tolerable Period of Disruption (MTPD)', type: 'text' },
      { name: 'Recovery Priority', label: 'Recovery Priority', type: 'number' }, //Extra Line Added here
      { name: 'Recovery Time Objective (RTO)', label: 'Recovery Time Objective (RTO)', type: 'text' },
      { name: 'Staff Requirement', label: 'Staff Requirement', type: 'number' },
      { name: 'Facilities & Workspace Requirements', label: 'Facilities & Workspace Requirements', type: 'text' },
      { name: 'Critical Records', label: 'Critical Records', type: 'text' },
      { name: 'Applications& Technology', label: 'Applications& Technology', type: 'text' },
      { name: 'Suppliers / Partners', label: 'Suppliers / Partners', type: 'text' },
      { name: 'Short-Term Workarounds?', label: 'Short-Term Workarounds?', type: 'text' },
      { name: 'Existing Response & Recovery Plans?', label: 'Existing Response & Recovery Plans?', type: 'text' },
      { name: 'MTDL Max. Tolerable Data Loss', label: 'MTDL Max. Tolerable Data Loss', type: 'text' },
      { name: 'RPO Recovery Point Objective', label: 'RPO Recovery Point Objective', type: 'text' },
      { name: 'Additional Information', label: 'Additional Information', type: 'text' }
    ],
    'Raw Material': [
      { name: 'Key Function / Service', label: 'Key Function / Service', type: 'text' },
      { name: 'Key Function / Service Owner(s)', label: 'Key Function / Service Owner(s)', type: 'text' },
      { name: 'Time From Start Of Incident', label: 'Time From Start Of Incident', type: 'text' },
      { name: 'Impact To Company', label: 'Impact To Company', type: 'text' },
      { name: 'Justification for Impact to Company (Based on Financial / Operational / Legal Reasons)', label: 'Justification for Impact to Company (Based on Financial / Operational / Legal Reasons)', type: 'text' },
      { name: 'Who is Impacted', label: 'Who is Impacted', type: 'text' },
      { name: 'Max. Tolerable Period of Disruption (MTPD)', label: 'Max. Tolerable Period of Disruption (MTPD)', type: 'text' },
      { name: 'Recovery Time Objective (RTO)', label: 'Recovery Time Objective (RTO)', type: 'text' },
      { name: 'Staff Requirement', label: 'Staff Requirement', type: 'number' },
      { name: 'Facilities & Workspace Requirements', label: 'Facilities & Workspace Requirements', type: 'text' },
      { name: 'Critical Records', label: 'Critical Records', type: 'text' },
      { name: 'Applications& Technology', label: 'Applications& Technology', type: 'text' },
      { name: 'Suppliers / Partners', label: 'Suppliers / Partners', type: 'text' },
      { name: 'Short-Term Workarounds?', label: 'Short-Term Workarounds?', type: 'text' },
      { name: 'Existing Response & Recovery Plans?', label: 'Existing Response & Recovery Plans?', type: 'text' },
      { name: 'MTDL Max. Tolerable Data Loss', label: 'MTDL Max. Tolerable Data Loss', type: 'text' },
      { name: 'RPO Recovery Point Objective', label: 'RPO Recovery Point Objective', type: 'text' },
      { name: 'Additional Information', label: 'Additional Information', type: 'text' }
    ],
    'Sales & Marketing': [
      { name: 'Key Function / Service', label: 'Key Function / Service', type: 'text' },
      { name: 'Key Function / Service Owner(s)', label: 'Key Function / Service Owner(s)', type: 'text' },
      { name: 'Time From Start Of Incident', label: 'Time From Start Of Incident', type: 'text' },
      { name: 'Impact To Company', label: 'Impact To Company', type: 'text' },
      { name: 'Justification for Impact to Company (Based on Financial / Operational / Legal Reasons)', label: 'Justification for Impact to Company (Based on Financial / Operational / Legal Reasons)', type: 'text' },
      { name: 'Who is Impacted', label: 'Who is Impacted', type: 'text' },
      { name: 'Max. Tolerable Period of Disruption (MTPD)', label: 'Max. Tolerable Period of Disruption (MTPD)', type: 'text' },
      // { name: 'Recovery Priority', label: 'Recovery Priority', type: 'number' },
      { name: 'Recovery Time Objective (RTO)', label: 'Recovery Time Objective (RTO)', type: 'text' },
      { name: 'Staff Requirement', label: 'Staff Requirement', type: 'number' },
      { name: 'Facilities & Workspace Requirements', label: 'Facilities & Workspace Requirements', type: 'text' },
      { name: 'Critical Records', label: 'Critical Records', type: 'text' },
      { name: 'Applications& Technology', label: 'Applications& Technology', type: 'text' },
      { name: 'Suppliers / Partners', label: 'Suppliers / Partners', type: 'text' },
      { name: 'Short-Term Workarounds?', label: 'Short-Term Workarounds?', type: 'text' },
      { name: 'Existing Response & Recovery Plans?', label: 'Existing Response & Recovery Plans?', type: 'text' },
      { name: 'MTDL Max. Tolerable Data Loss', label: 'MTDL Max. Tolerable Data Loss', type: 'text' },
      { name: 'RPO Recovery Point Objective', label: 'RPO Recovery Point Objective', type: 'text' },
      { name: 'Additional Information', label: 'Additional Information', type: 'text' }
    ],
    'Shipping': [
      { name: 'Key Function / Service', label: 'Key Function / Service', type: 'text' },
      { name: 'Key Function / Service Owner(s)', label: 'Key Function / Service Owner(s)', type: 'text' },
      { name: 'Time From Start Of Incident', label: 'Time From Start Of Incident', type: 'text' },
      { name: 'Impact To Company', label: 'Impact To Company', type: 'text' },
      { name: 'Justification for Impact to Company (Based on Financial / Operational / Legal Reasons)', label: 'Justification for Impact to Company (Based on Financial / Operational / Legal Reasons)', type: 'text' },
      { name: 'Who is Impacted', label: 'Who is Impacted', type: 'text' },
      { name: 'Max. Tolerable Period of Disruption (MTPD)', label: 'Max. Tolerable Period of Disruption (MTPD)', type: 'text' },
      // { name: 'Recovery Priority', label: 'Recovery Priority', type: 'number' },
      { name: 'Recovery Time Objective (RTO)', label: 'Recovery Time Objective (RTO)', type: 'text' },
      { name: 'Staff Requirement', label: 'Staff Requirement', type: 'number' },
      { name: 'Facilities & Workspace Requirements', label: 'Facilities & Workspace Requirements', type: 'text' },
      { name: 'Critical Records', label: 'Critical Records', type: 'text' },
      { name: 'Applications& Technology', label: 'Applications& Technology', type: 'text' },
      { name: 'Suppliers / Partners', label: 'Suppliers / Partners', type: 'text' },
      { name: 'Short-Term Workarounds?', label: 'Short-Term Workarounds?', type: 'text' },
      { name: 'Existing Response & Recovery Plans?', label: 'Existing Response & Recovery Plans?', type: 'text' },
      { name: 'MTDL Max. Tolerable Data Loss', label: 'MTDL Max. Tolerable Data Loss', type: 'text' },
      { name: 'RPO Recovery Point Objective', label: 'RPO Recovery Point Objective', type: 'text' },
      { name: 'Additional Information', label: 'Additional Information', type: 'text' }
    ],
  }
};

export default formStructure;
